/**
 * Rasterises the SVG assets and renders the social card.
 *
 *   node brand/render.mjs
 *
 * Run brand/make-brand.py first — that produces the SVGs this reads.
 */
import { chromium } from 'playwright';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const BRAND = dirname(fileURLToPath(import.meta.url));
const svg = (p) => readFileSync(resolve(BRAND, p), 'utf8');

const INK = '#2B2D24';
const PAPER = '#E7E5DC';
const MUTED = '#6E7264';
const SIGNAL = '#A82A57';
const LINE = '#C9C6B8';

const FONTS =
  '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' +
  '<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,300..800&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">';

const browser = await chromium.launch();

async function shoot(html, { width, height, path, scale = 1, fullPage = false }) {
  const page = await browser.newPage({
    viewport: { width, height },
    deviceScaleFactor: scale,
  });
  await page.setContent(
    `<!doctype html><meta charset="utf-8">${FONTS}<style>*{margin:0;box-sizing:border-box}</style>${html}`,
    { waitUntil: 'networkidle' },
  );
  await page.waitForTimeout(500);
  mkdirSync(dirname(resolve(BRAND, path)), { recursive: true });
  await page.screenshot({ path: resolve(BRAND, path), fullPage, omitBackground: !fullPage });
  await page.close();
  console.log('  ', path);
}

// --- app icons -------------------------------------------------------------
const plate = svg('logo/detent-mark-plate.svg');
for (const size of [32, 180, 512]) {
  await shoot(
    `<body style="width:${size}px;height:${size}px">${plate.replace(
      /width="48" height="48"/,
      `width="${size}" height="${size}"`,
    )}</body>`,
    { width: size, height: size, path: `favicon/icon-${size}.png` },
  );
}

// --- social card -----------------------------------------------------------
const lockup = svg('logo/detent-lockup.svg');
await shoot(
  `<body style="width:1200px;height:630px;background:${PAPER};font-family:'Bricolage Grotesque',sans-serif;
     background-image:linear-gradient(to right,rgba(43,45,36,.05) 1px,transparent 1px),
                      linear-gradient(to bottom,rgba(43,45,36,.05) 1px,transparent 1px);
     background-size:40px 40px;display:flex;flex-direction:column;justify-content:center;padding:0 88px;gap:34px">
     <div style="height:74px">${lockup.replace(/height="48"/, 'height="74"')}</div>
     <div style="font-size:46px;font-weight:600;letter-spacing:-.035em;color:${INK};line-height:1.12;max-width:22ch">
       Drag, reorder and resize.<br>Nothing else.</div>
     <div style="display:flex;gap:26px;font-family:'JetBrains Mono',monospace;font-size:19px;color:${MUTED}">
       <span><b style="color:${INK}">5.8 KB</b> gzipped</span>
       <span><b style="color:${INK}">0</b> dependencies</span>
       <span>mouse · touch · pen · keyboard</span></div>
   </body>`,
  { width: 1200, height: 630, path: 'social/og-image.png', fullPage: true },
);

// --- brand sheet -----------------------------------------------------------
const swatch = (name, hex, note) => `
  <div style="min-width:0">
    <div style="height:74px;border-radius:3px;background:${hex};border:1px solid ${LINE}"></div>
    <div style="margin-top:8px;font-size:13px;font-weight:600">${name}</div>
    <div style="font-family:'JetBrains Mono',monospace;font-size:11px;color:${MUTED}">${hex}</div>
    <div style="font-size:12px;color:${MUTED};margin-top:2px">${note}</div>
  </div>`;

const section = (title, body) => `
  <section style="padding:34px 0;border-bottom:1px solid ${LINE}">
    <h2 style="font-size:13px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:${MUTED};margin-bottom:18px">${title}</h2>
    ${body}
  </section>`;

const sheet = `<body style="background:${PAPER};color:${INK};font-family:'Bricolage Grotesque',sans-serif;padding:56px 64px 80px;width:1100px">
  <div style="height:56px;margin-bottom:10px">${lockup.replace(/height="48"/, 'height="56"')}</div>
  <p style="color:${MUTED};font-size:15px;margin-bottom:14px">Brand sheet — generated by brand/make-brand.py and brand/render.mjs</p>

  ${section(
    'The mark',
    `<div style="display:flex;align-items:flex-end;gap:48px;flex-wrap:wrap">
      <div>${plate.replace(/width="48" height="48"/, 'width="96" height="96"')}</div>
      <div style="height:64px">${svg('logo/detent-mark.svg').replace(/width="48" height="48"/, 'width="64" height="64"')}</div>
      <div style="height:40px">${svg('logo/detent-mark.svg').replace(/width="48" height="48"/, 'width="40" height="40"')}</div>
      <div style="height:24px">${svg('logo/detent-mark.svg').replace(/width="48" height="48"/, 'width="24" height="24"')}</div>
      <p style="flex:1;min-width:280px;font-size:14px;color:${MUTED};max-width:44ch">
        A part resting in its seat. Two shapes and nothing else, so it survives being
        shrunk. Below about 24px use the plate version — the open mark loses its seat.</p>
    </div>`,
  )}

  ${section(
    'Lockup',
    `<div style="display:flex;align-items:center;gap:56px;flex-wrap:wrap">
      <div style="height:48px">${lockup}</div>
      <div style="height:28px">${lockup.replace(/height="48"/, 'height="28"')}</div>
      <div style="background:${INK};padding:18px 26px;border-radius:3px;height:84px;display:flex;align-items:center">
        <div style="height:44px">${svg('logo/detent-lockup-inverse.svg').replace(/height="48"/, 'height="44"')}</div>
      </div>
    </div>
    <p style="font-size:14px;color:${MUTED};margin-top:16px;max-width:60ch">
      Clear space around the lockup is the height of the mark on every side. The word
      is always lowercase and never re-set in another face — use the supplied file.</p>`,
  )}

  ${section(
    'Colour',
    `<div style="display:grid;grid-template-columns:repeat(7,1fr);gap:12px">
      ${swatch('Ink', INK, 'Text, the rail, dark surfaces')}
      ${swatch('Paper', PAPER, 'Page background')}
      ${swatch('Panel', '#FAF9F5', 'Raised surfaces')}
      ${swatch('Signal', SIGNAL, 'The seated part, active states')}
      ${swatch('Signal soft', '#F4DEE6', 'Active fills, highlights')}
      ${swatch('Muted', MUTED, 'Secondary text')}
      ${swatch('Line', LINE, 'Rules and borders')}
    </div>
    <p style="font-size:14px;color:${MUTED};margin-top:16px;max-width:60ch">
      Signal is for the thing that just moved, never for body text on Paper. One accent
      only — a second colour undoes the point of having one.</p>`,
  )}

  ${section(
    'Type',
    `<div style="display:flex;gap:64px;flex-wrap:wrap">
      <div>
        <div style="font-size:44px;font-weight:700;letter-spacing:-.035em">Bricolage Grotesque</div>
        <div style="font-size:13px;color:${MUTED};margin-top:4px">Display and interface · 300–800</div>
      </div>
      <div>
        <div style="font-family:'JetBrains Mono',monospace;font-size:34px;font-weight:600">JetBrains Mono</div>
        <div style="font-size:13px;color:${MUTED};margin-top:4px">Code, measurements, readouts · 400/600</div>
      </div>
    </div>`,
  )}

  ${section(
    'Voice',
    `<div style="display:flex;gap:48px;flex-wrap:wrap;font-size:15px;max-width:78ch">
      <ul style="flex:1;min-width:240px;padding-left:18px;line-height:1.75">
        <li>Say what it does, not what it feels like.</li>
        <li>Numbers over adjectives: "5.8 KB", not "tiny".</li>
        <li>Lowercase package name, sentence case everywhere else.</li>
      </ul>
      <ul style="flex:1;min-width:240px;padding-left:18px;line-height:1.75;color:${MUTED}">
        <li>No "blazingly fast", no "buttery smooth".</li>
        <li>Don't claim it replaces anything.</li>
        <li>Name the trade-off when there is one.</li>
      </ul>
    </div>`,
  )}
</body>`;

await shoot(sheet, { width: 1100, height: 1400, path: 'brand-sheet.png', scale: 2, fullPage: true });
writeFileSync(resolve(BRAND, 'brand-sheet.html'), `<!doctype html><meta charset="utf-8">${FONTS}<style>*{margin:0;box-sizing:border-box}</style>${sheet}`);
console.log('   brand-sheet.html');

await browser.close();
